after :sites do
  Loop.seed(:id,
    {id: 1, name: 'Main Loop', site_id: 1, is_active: true, station_count: 10},
    {id: 2, name: 'Main Loop', site_id: 2, is_active: false, station_count: 8},
    {id: 3, name: 'Pipers Creek Loop', site_id: 3, is_active: true, station_count: 7},
    {id: 4, name: 'Venema Meadow Loop', site_id: 3, is_active: true, station_count: 9},
    {id: 5, name: 'Main Loop', site_id: 4, is_active: false, station_count: 1},
    {id: 6, name: 'Beaches', site_id: 5, is_active: true, station_count: 7},
    {id: 7, name: 'Capehart', site_id: 5, is_active: true, station_count: 6},
    {id: 8, name: 'Cemetery', site_id: 5, is_active: true, station_count: 8},
    {id: 9, name: 'Daybreak Star', site_id: 5, is_active: true, station_count: 8},
    {id: 10, name: 'Eastern Edge', site_id: 5, is_active: true, station_count: 9},
    {id: 11, name: 'Hidden Valley Trail', site_id: 5, is_active: true, station_count: 8},
    {id: 12, name: 'Nike/500', site_id: 5, is_active: true, station_count: 5},
    {id: 13, name: 'North Beach Trail', site_id: 5, is_active: true, station_count: 5},
    {id: 14, name: 'North Loop Trail', site_id: 5, is_active: true, station_count: 9},
    {id: 15, name: 'South Beach Trail', site_id: 5, is_active: true, station_count: 7},
    {id: 16, name: 'South Loop Trail', site_id: 5, is_active: true, station_count: 10},
    {id: 17, name: 'South Meadow', site_id: 5, is_active: true, station_count: 9},
    {id: 18, name: 'Wolf Tree Nature Trail', site_id: 5, is_active: true, station_count: 7},
    {id: 19, name: 'Main Loop', site_id: 6, is_active: true, station_count: 7},
    {id: 20, name: 'Main Loop', site_id: 7, is_active: true, station_count: 6},
    {id: 21, name: 'Main Loop', site_id: 8, is_active: false, station_count: 1},
    {id: 22, name: 'Main Loop', site_id: 9, is_active: true, station_count: 2},
    {id: 23, name: 'Fence Loop', site_id: 10, is_active: true, station_count: 6},
    {id: 24, name: 'Main Drag Loop', site_id: 10, is_active: true, station_count: 5},
    {id: 25, name: 'Southend Loop', site_id: 10, is_active: true, station_count: 6},
    {id: 26, name: 'Waterfront Loop', site_id: 10, is_active: true, station_count: 8},
    {id: 27, name: 'Wetland Loop', site_id: 10, is_active: true, station_count: 4},
    {id: 28, name: 'East Loop', site_id: 11, is_active: true, station_count: 8},
    {id: 29, name: 'West Loop', site_id: 11, is_active: true, station_count: 8},
    {id: 30, name: 'Main Loop', site_id: 12, is_active: false, station_count: 8},
    {id: 31, name: 'Main Loop', site_id: 13, is_active: false, station_count: 4},
    {id: 32, name: 'Creek Loop', site_id: 14, is_active: false, station_count: 10},
    {id: 33, name: 'Pipeline Loop', site_id: 14, is_active: false, station_count: 6}
  )
end
