[
  ['Accipiter sp.'],
  ['American Black Duck', 'ABDU'],
  ['American Coot', 'AMCO'],
  ['American Crow', 'AMCR'],
  ['American Dipper', 'AMDI'],
  ['American Goldfinch', 'AMGO'],
  ['American Kestrel', 'AMKE'],
  ['American Pipit', 'AMPI'],
  ['American Robin', 'AMRO'],
  ['American Wigeon', 'AMWI'],
  ['American x Eurasian Wigeon'],
  ['Anna\'s Hummingbird', 'ANHU'],
  ['Baird\'s Sandpiper', 'BASA'],
  ['Bald Eagle', 'BAEA'],
  ['Band-tailed Pigeon', 'BTPI'],
  ['Bank Swallow', 'BANS'],
  ['Barn Owl', 'BANO'],
  ['Barn Swallow', 'BARS'],
  ['Barred Owl', 'BADO'],
  ['Barrow\'s Goldeneye', 'BAGO'],
  ['Belted Kingfisher', 'BEKI'],
  ['Bewick\'s Wren', 'BEWR'],
  ['Black Phoebe', 'BLPH'],
  ['Black Scoter', 'BLSC'],
  ['Black Swift', 'BLSW'],
  ['Black Turnstone', 'BLTU'],
  ['Black-backed Woodpecker', 'BBWO'],
  ['Black-bellied Plover', 'BBPL'],
  ['Black-capped Chickadee', 'BCCH'],
  ['Black-headed Grosbeak', 'BHGR'],
  ['Black-throated Gray Warbler', 'BTYW'],
  ['Blue Jay', 'BLJA'],
  ['Blue-winged Teal', 'BWTE'],
  ['Bonaparte\'s Gull', 'BOGU'],
  ['Brandt\'s Cormorant', 'BRAC'],
  ['Brant', 'BRAN'],
  ['Brewer\'s Blackbird', 'BRBL'],
  ['Brown Creeper', 'BRCR'],
  ['Brown-headed Cowbird', 'BHCO'],
  ['Bufflehead', 'BUFF'],
  ['Bullock\'s Oriole', 'BUOR'],
  ['Bushtit', 'BUSH'],
  ['Cackling Goose', 'CACG'],
  ['California Gull', 'CAGU'],
  ['California Quail', 'CAQU'],
  ['California Scrub-Jay', 'CASJ'],
  ['Canada Goose', 'CANG'],
  ['Canvasback', 'CANV'],
  ['Caspian Tern', 'CATE'],
  ['Cassin\'s Vireo', 'CAVI'],
  ['Cedar Waxwing', 'CEDW'],
  ['Chestnut-backed Chickadee', 'CBCH'],
  ['Chickadee sp.'],
  ['Chipping Sparrow', 'CHSP'],
  ['Cinnamon Teal', 'CITE'],
  ['Cliff Swallow', 'CLSW'],
  ['Common Goldeneye', 'COGO'],
  ['Common Loon', 'COLO'],
  ['Common Merganser', 'COME'],
  ['Common Murre', 'COMU'],
  ['Common Raven', 'CORA'],
  ['Common Tern', 'COTE'],
  ['Common Yellowthroat', 'COYE'],
  ['Cooper\'s Hawk', 'COHA'],
  ['Dark-eyed Junco', 'DEJU'],
  ['Domestic Goose'],
  ['Double-crested Cormorant', 'DCCO'],
  ['Downy Woodpecker', 'DOWO'],
  ['Dove sp.'],
  ['Duck sp.'],
  ['Dunlin', 'DUNL'],
  ['Eared Grebe', 'EAGR'],
  ['Empidonax sp.'],
  ['Eurasian Collared-Dove', 'EUCD'],
  ['Eurasian Wigeon', 'EUWI'],
  ['European Goldfinch', 'EUGO'],
  ['European Starling', 'EUST'],
  ['Evening Grosbeak', 'EVGR'],
  ['Falcon sp.'],
  ['Finch sp.'],
  ['Flycatcher sp.'],
  ['Forster\'s Tern', 'FOTE'],
  ['Fox Sparrow', 'FOSP'],
  ['Franklin\'s Gull', 'FRGU'],
  ['Gadwall', 'GADW'],
  ['Glaucous-winged Gull', 'GWGU'],
  ['Glaucous-winged x Western Gull'],
  ['Golden Eagle', 'GOEA'],
  ['Golden-crowned Kinglet', 'GCKI'],
  ['Golden-crowned Sparrow', 'GCSP'],
  ['Goldeneye sp.'],
  ['Goose sp.'],
  ['Great Blue Heron', 'GBHE'],
  ['Great Horned Owl', 'GHOW'],
  ['Greater Scaup', 'GRSC'],
  ['Greater White-fronted Goose', 'GWFG'],
  ['Greater Yellowlegs', 'GRYE'],
  ['Grebe sp.'],
  ['Green Heron', 'GRHE'],
  ['Green-winged Teal', 'GWTE'],
  ['Gull sp.'],
  ['Hairy Woodpecker', 'HAWO'],
  ['Hammond\'s Flycatcher', 'HAFL'],
  ['Harlequin Duck', 'HADU'],
  ['Hawk sp.'],
  ['Heermann\'s Gull', 'HEEG'],
  ['Hermit Thrush', 'HETH'],
  ['Hermit Warbler', 'HEWA'],
  ['Herring Gull', 'HERG'],
  ['Hooded Merganser', 'HOME'],
  ['Horned Grebe', 'HOGR'],
  ['Horned Lark', 'HOLA'],
  ['House Finch', 'HOFI'],
  ['House Sparrow', 'HOSP'],
  ['House Wren', 'HOWR'],
  ['Hummingbird sp.'],
  ['Hutton\'s Vireo', 'HUVI'],
  ['Killdeer', 'KILL'],
  ['Kinglet sp.'],
  ['Lark Sparrow', 'LASP'],
  ['Lazuli Bunting', 'LAZB'],
  ['Least Sandpiper', 'LESA'],
  ['Lesser Scaup', 'LESC'],
  ['Lincoln\'s Sparrow', 'LISP'],
  ['Long-billed Dowitcher', 'LBDO'],
  ['Long-tailed Duck', 'LTDU'],
  ['Loon sp.'],
  ['MacGillivray\'s Warbler', 'MGWA'],
  ['Mallard', 'MALL'],
  ['Marbled Murrelet', 'MAMU'],
  ['Marsh Wren', 'MAWR'],
  ['Merganser sp.'],
  ['Merlin', 'MERL'],
  ['Mew Gull', 'MEGU'],
  ['Mitred Parakeet', 'MIPA'],
  ['Mountain Chickadee', 'MOCH'],
  ['Mourning Dove', 'MODO'],
  ['Nashville Warbler', 'NAWA'],
  ['Northern Flicker', 'NOFL'],
  ['Northern Harrier', 'NOHA'],
  ['Northern Pintail', 'NOPI'],
  ['Northern Rough-winged Swallow', 'NRWS'],
  ['Northern Saw-whet Owl', 'NSWO'],
  ['Northern Shoveler', 'NSHO'],
  ['Northern Shrike', 'NSHR'],
  ['Northwestern Crow', 'NOCR'],
  ['Olive-sided Flycatcher', 'OSFL'],
  ['Orange-crowned Warbler', 'OCWA'],
  ['Osprey', 'OSPR'],
  ['Owl sp.'],
  ['Pacific Loon', 'PALO'],
  ['Pacific Wren', 'PAWR'],
  ['Pacific-slope Flycatcher', 'PSFL'],
  ['Parasitic Jaeger', 'PAJA'],
  ['Parrot sp.'],
  ['Passerine sp.'],
  ['Pectoral Sandpiper', 'PESA'],
  ['Pelagic Cormorant', 'PECO'],
  ['Peregrine Falcon', 'PEFA'],
  ['Pied-billed Grebe', 'PBGR'],
  ['Pigeon Guillemot', 'PIGU'],
  ['Pigeon sp.'],
  ['Pileated Woodpecker', 'PIWO'],
  ['Pine Grosbeak', 'PIGR'],
  ['Pine Siskin', 'PISI'],
  ['Purple Finch', 'PUFI'],
  ['Purple Martin', 'PUMA'],
  ['Red Crossbill', 'RECR'],
  ['Red-breasted Merganser', 'RBME'],
  ['Red-breasted Nuthatch', 'RBNU'],
  ['Red-breasted Sapsucker', 'RBSA'],
  ['Red-eyed Vireo', 'REVI'],
  ['Red-necked Grebe', 'RNGR'],
  ['Red-tailed Hawk', 'RTHA'],
  ['Red-throated Loon', 'RTLO'],
  ['Red-winged Blackbird', 'RWBL'],
  ['Redhead', 'REDH'],
  ['Rhinoceros Auklet', 'RHAU'],
  ['Ring-billed Gull', 'RBGU'],
  ['Ring-necked Duck', 'RNDU'],
  ['Ring-necked Pheasant', 'RNEP'],
  ['Rock Pigeon', 'ROPI'],
  ['Rock Wren', 'ROWR'],
  ['Rose-breasted Grosbeak', 'RBGR'],
  ['Ruby-crowned Kinglet', 'RCKI'],
  ['Ruddy Duck', 'RUDU'],
  ['Rufous Hummingbird', 'RUHU'],
  ['Sanderling', 'SAND'],
  ['Sandpiper sp.'],
  ['Savannah Sparrow', 'SAVS'],
  ['Say\'s Phoebe', 'SAPH'],
  ['Scaup sp.'],
  ['Semipalmated Plover', 'SEPL'],
  ['Sharp-shinned Hawk', 'SSHA'],
  ['Short-eared Owl', 'SEOW'],
  ['Snow Bunting', 'SNBU'],
  ['Snow Goose', 'SNGO'],
  ['Snowy Owl', 'SNOW'],
  ['Song Sparrow', 'SOSP'],
  ['Sora', 'SORA'],
  ['Sparrow sp.'],
  ['Spotted Owl', 'SPOW'],
  ['Spotted Sandpiper', 'SPSA'],
  ['Spotted Towhee', 'SPTO'],
  ['Steller\'s Jay', 'STJA'],
  ['Surf Scoter', 'SUSC'],
  ['Surfbird', 'SURF'],
  ['Swainson\'s Thrush', 'SWTH'],
  ['Swallow sp.'],
  ['Swan sp.'],
  ['Tern sp.'],
  ['Thayer\'s Gull', 'THGU'],
  ['Thrush sp.'],
  ['Townsend\'s Solitaire', 'TOSO'],
  ['Townsend\'s Warbler', 'TOWA'],
  ['Tree Swallow', 'TRES'],
  ['Trumpeter Swan', 'TRUS'],
  ['Turkey Vulture', 'TUVU'],
  ['Varied Thrush', 'VATH'],
  ['Vaux\'s Swift', 'VASW'],
  ['Vesper Sparrow', 'VESP'],
  ['Violet-green Swallow', 'VGSW'],
  ['Vireo sp.'],
  ['Virginia Rail', 'VIRA'],
  ['Warbler sp.'],
  ['Warbling Vireo', 'WAVI'],
  ['Western Bluebird', 'WEBL'],
  ['Western Grebe', 'WEGR'],
  ['Western Gull', 'WEGU'],
  ['Western Kingbird', 'WEKI'],
  ['Western Meadowlark', 'WEME'],
  ['Western Sandpiper', 'WESA'],
  ['Western Tanager', 'WETA'],
  ['Western Wood-Pewee', 'WEWP'],
  ['Whimbrel', 'WHIM'],
  ['White-crowned Sparrow', 'WCSP'],
  ['White-throated Sparrow', 'WTSP'],
  ['White-winged Scoter', 'WWSC'],
  ['Willow Flycatcher', 'WIFL'],
  ['Wilson\'s Snipe', 'WISN'],
  ['Wilson\'s Warbler', 'WIWA'],
  ['Wood Duck', 'WODU'],
  ['Woodpecker sp.'],
  ['Wren sp.'],
  ['Yellow Warbler', 'YEWA'],
  ['Yellow-rumped Warbler', 'YRWA']
].each_with_index do |taxon, i|
  Taxon.seed(:id, { id: i+1, common_name: taxon[0], banding_code: taxon[1] })
end
